# Generated by Django 5.2 on 2025-04-06 09:05

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_created_at_alter_document_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentchunk',
            old_name='chunk_text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
